/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>                                             // Includes declarations from sys/stat.h required by this source file.
#include <stdlib.h>                                               // Includes declarations from stdlib.h required by this source file.
#include <errno.h>                                                // Includes declarations from errno.h required by this source file.
#include <stdio.h>                                                // Includes declarations from stdio.h required by this source file.
#include <signal.h>                                               // Includes declarations from signal.h required by this source file.
#include <time.h>                                                 // Includes declarations from time.h required by this source file.
#include <sys/time.h>                                             // Includes declarations from sys/time.h required by this source file.
#include <sys/times.h>                                            // Includes declarations from sys/times.h required by this source file.


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));            // Executes this statement as part of the current control flow.
extern int __io_getchar(void) __attribute__((weak));              // Executes this statement as part of the current control flow.


char *__env[1] = { 0 };                                           // Sets char *__env[1] to { 0 }.
char **environ = __env;                                           // Sets char **environ to __env.


/* Functions */
void initialise_monitor_handles()                                 // Defines the initialise_monitor_handles function.
{                                                                 // Opens the current code block.
}                                                                 // Closes the current code block.

int _getpid(void)                                                 // Defines the _getpid function.
{                                                                 // Opens the current code block.
  return 1;                                                       // Returns 1 to the caller.
}                                                                 // Closes the current code block.

int _kill(int pid, int sig)                                       // Defines the _kill function.
{                                                                 // Opens the current code block.
  (void)pid;                                                      // Marks pid as intentionally unused to avoid compiler warnings.
  (void)sig;                                                      // Marks sig as intentionally unused to avoid compiler warnings.
  errno = EINVAL;                                                 // Sets errno to EINVAL.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

void _exit (int status)                                           // Defines the _exit function.
{                                                                 // Opens the current code block.
  _kill(status, -1);                                              // Calls _kill with the configured arguments.
  while (1) {}    /* Make sure we hang here */
}                                                                 // Closes the current code block.

__attribute__((weak)) int _read(int file, char *ptr, int len)     // Defines the low-level read system call used by the C runtime.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  int DataIdx;                                                    // Declares DataIdx as a int variable used by this module.

  for (DataIdx = 0; DataIdx < len; DataIdx++)                     // Iterates over the configured loop range.
  {                                                               // Opens the current code block.
    *ptr++ = __io_getchar();                                      // Sets *ptr++ to __io_getchar().
  }                                                               // Closes the current code block.

  return len;                                                     // Returns len to the caller.
}                                                                 // Closes the current code block.

__attribute__((weak)) int _write(int file, char *ptr, int len)    // Defines the low-level write function used to redirect standard output.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  int DataIdx;                                                    // Declares DataIdx as a int variable used by this module.

  for (DataIdx = 0; DataIdx < len; DataIdx++)                     // Iterates over the configured loop range.
  {                                                               // Opens the current code block.
    __io_putchar(*ptr++);                                         // Calls __io_putchar with the configured arguments.
  }                                                               // Closes the current code block.
  return len;                                                     // Returns len to the caller.
}                                                                 // Closes the current code block.

int _close(int file)                                              // Defines the _close function.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.


int _fstat(int file, struct stat *st)                             // Defines the _fstat function.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  st->st_mode = S_IFCHR;                                          // Sets st->st_mode to S_IFCHR.
  return 0;                                                       // Returns 0 to the caller.
}                                                                 // Closes the current code block.

int _isatty(int file)                                             // Defines the _isatty function.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  return 1;                                                       // Returns 1 to the caller.
}                                                                 // Closes the current code block.

int _lseek(int file, int ptr, int dir)                            // Defines the _lseek function.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  (void)ptr;                                                      // Marks ptr as intentionally unused to avoid compiler warnings.
  (void)dir;                                                      // Marks dir as intentionally unused to avoid compiler warnings.
  return 0;                                                       // Returns 0 to the caller.
}                                                                 // Closes the current code block.

int _open(char *path, int flags, ...)                             // Defines the _open function.
{                                                                 // Opens the current code block.
  (void)path;                                                     // Marks path as intentionally unused to avoid compiler warnings.
  (void)flags;                                                    // Marks flags as intentionally unused to avoid compiler warnings.
  /* Pretend like we always fail */
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

int _wait(int *status)                                            // Defines the _wait function.
{                                                                 // Opens the current code block.
  (void)status;                                                   // Marks status as intentionally unused to avoid compiler warnings.
  errno = ECHILD;                                                 // Sets errno to ECHILD.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

int _unlink(char *name)                                           // Defines the _unlink function.
{                                                                 // Opens the current code block.
  (void)name;                                                     // Marks name as intentionally unused to avoid compiler warnings.
  errno = ENOENT;                                                 // Sets errno to ENOENT.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

clock_t _times(struct tms *buf)                                   // Continues the current multi-line expression or function call.
{                                                                 // Opens the current code block.
  (void)buf;                                                      // Marks buf as intentionally unused to avoid compiler warnings.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

int _stat(const char *file, struct stat *st)                      // Defines the _stat function.
{                                                                 // Opens the current code block.
  (void)file;                                                     // Marks file as intentionally unused to avoid compiler warnings.
  st->st_mode = S_IFCHR;                                          // Sets st->st_mode to S_IFCHR.
  return 0;                                                       // Returns 0 to the caller.
}                                                                 // Closes the current code block.

int _link(char *old, char *new)                                   // Defines the _link function.
{                                                                 // Opens the current code block.
  (void)old;                                                      // Marks old as intentionally unused to avoid compiler warnings.
  (void)new;                                                      // Marks new as intentionally unused to avoid compiler warnings.
  errno = EMLINK;                                                 // Sets errno to EMLINK.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

int _fork(void)                                                   // Defines the _fork function.
{                                                                 // Opens the current code block.
  errno = EAGAIN;                                                 // Sets errno to EAGAIN.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

int _execve(char *name, char **argv, char **env)                  // Defines the _execve function.
{                                                                 // Opens the current code block.
  (void)name;                                                     // Marks name as intentionally unused to avoid compiler warnings.
  (void)argv;                                                     // Marks argv as intentionally unused to avoid compiler warnings.
  (void)env;                                                      // Marks env as intentionally unused to avoid compiler warnings.
  errno = ENOMEM;                                                 // Sets errno to ENOMEM.
  return -1;                                                      // Returns -1 to the caller.
}                                                                 // Closes the current code block.

// --- Picolibc Specific Section ---
#if defined(__PICOLIBC__)                                         // Compiles the following block only when this preprocessor condition is true.

/**
 * @brief Picolibc helper function to output a character to a FILE stream.
 *        This redirects the output to the low-level __io_putchar function.
 * @param c Character to write.
 * @param file FILE stream pointer (ignored).
 * @retval int The character written.
 */
static int starm_putc(char c, FILE *file)                         // Defines the starm_putc function.
{                                                                 // Opens the current code block.
	(void) file;                                                     // Continues the current multi-line expression or function call.
  __io_putchar(c);                                                // Calls __io_putchar with the configured arguments.
	return c;                                                        // Returns c to the caller.
}                                                                 // Closes the current code block.

/**
 * @brief Picolibc helper function to input a character from a FILE stream.
 *        This redirects the input from the low-level __io_getchar function.
 * @param file FILE stream pointer (ignored).
 * @retval int The character read, cast to an unsigned char then int.
 */
static int starm_getc(FILE *file)                                 // Defines the starm_getc function.
{                                                                 // Opens the current code block.
	unsigned char c;                                                 // Declares c as a char variable used by this module.
	(void) file;                                                     // Continues the current multi-line expression or function call.
  c = __io_getchar();                                             // Sets c to __io_getchar().
	return c;                                                        // Returns c to the caller.
}                                                                 // Closes the current code block.

// Define and initialize the standard I/O streams for Picolibc.
// FDEV_SETUP_STREAM connects the starm_putc and starm_getc helper functions to a FILE structure.
// _FDEV_SETUP_RW indicates the stream is for reading and writing.
static FILE __stdio = FDEV_SETUP_STREAM(starm_putc,               // Provides static FILE __stdio = FDEV_SETUP_STREAM(starm_putc as the next value or argument in the current multi-line expression.
					starm_getc,                                                  // Provides starm_getc as the next value or argument in the current multi-line expression.
					NULL,                                                        // Provides NULL as the next value or argument in the current multi-line expression.
					_FDEV_SETUP_RW);                                             // Executes this statement as part of the current control flow.

// Assign the standard stream pointers (stdin, stdout, stderr) to the initialized stream.
// Picolibc uses these pointers for standard I/O operations (printf, scanf, etc.).
FILE *const stdin = &__stdio;                                     // Sets FILE *const stdin to &__stdio.
__strong_reference(stdin, stdout);                                // Calls __strong_reference with the configured arguments.
__strong_reference(stdin, stderr);                                // Calls __strong_reference with the configured arguments.

// Create strong aliases mapping standard C library function names (without underscore)
// to the implemented system call stubs (with underscore). Picolibc uses these
// standard names internally, so this linking is required.
__strong_reference(_read, read);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_write, write);                                // Calls __strong_reference with the configured arguments.
__strong_reference(_times, times);                                // Calls __strong_reference with the configured arguments.
__strong_reference(_execve, execve);                              // Calls __strong_reference with the configured arguments.
__strong_reference(_fork, fork);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_link, link);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_unlink, unlink);                              // Calls __strong_reference with the configured arguments.
__strong_reference(_stat, stat);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_wait, wait);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_open, open);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_close, close);                                // Calls __strong_reference with the configured arguments.
__strong_reference(_lseek, lseek);                                // Calls __strong_reference with the configured arguments.
__strong_reference(_isatty, isatty);                              // Calls __strong_reference with the configured arguments.
__strong_reference(_fstat, fstat);                                // Calls __strong_reference with the configured arguments.
__strong_reference(_exit, exit);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_kill, kill);                                  // Calls __strong_reference with the configured arguments.
__strong_reference(_getpid, getpid);                              // Calls __strong_reference with the configured arguments.

#endif //__PICOLIBC__
