/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>                                                                 // Includes declarations from errno.h required by this source file.
#include <stdint.h>                                                                // Includes declarations from stdint.h required by this source file.
#include <stddef.h>                                                                // Includes declarations from stddef.h required by this source file.

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;                                            // Sets static uint8_t *__sbrk_heap_end to NULL.

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk(ptrdiff_t incr)                                                        // Continues the current multi-line expression or function call.
{                                                                                  // Opens the current code block.
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;    // Declares stack_limit and initializes it with (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size.
  const uint8_t *max_heap = (uint8_t *)stack_limit;                                // Sets const uint8_t *max_heap to (uint8_t *)stack_limit.
  uint8_t *prev_heap_end;                                                          // Executes this statement as part of the current control flow.

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)                                                     // Checks whether NULL == __sbrk_heap_end before executing the conditional block.
  {                                                                                // Opens the current code block.
    __sbrk_heap_end = &_end;                                                       // Sets __sbrk_heap_end to &_end.
  }                                                                                // Closes the current code block.

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)                                           // Checks whether __sbrk_heap_end + incr > max_heap before executing the conditional block.
  {                                                                                // Opens the current code block.
    errno = ENOMEM;                                                                // Sets errno to ENOMEM.
    return (void *)-1;                                                             // Returns (void *)-1 to the caller.
  }                                                                                // Closes the current code block.

  prev_heap_end = __sbrk_heap_end;                                                 // Sets prev_heap_end to __sbrk_heap_end.
  __sbrk_heap_end += incr;                                                         // Sets __sbrk_heap_end + to incr.

  return (void *)prev_heap_end;                                                    // Returns (void *)prev_heap_end to the caller.
}                                                                                  // Closes the current code block.

#if defined(__PICOLIBC__)                                                          // Compiles the following block only when this preprocessor condition is true.
  // Picolibc expects syscalls without the leading underscore.
  // This creates a strong alias so that
  // calls to `sbrk()` are resolved to our `_sbrk()` implementation.
  __strong_reference(_sbrk, sbrk);                                                 // Calls __strong_reference with the configured arguments.
#endif                                                                             // Ends the current conditional-compilation block.
